#!/bin/bash
# chkconfig:   - 25 75
# description: chef-deregistration-manager
# processname: chef-deregistration-manager

# Source function library.
if [ -e /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions;
fi;

DAEMON_DIR="/usr/bin"
DAEMON=""

start(){
    echo "Starting $DAEMON..."
    # TODO: Issue client registration commands
    #/usr/bin/env python ${DAEMON_DIR}/${DAEMON}
    if [ $? -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi;
    echo ""
}

stop(){
    echo "Stopping $DAEMON..."
    # TODO: Check Runlevel, if 0, then do stop, else, exit 0.
    #pkill -f ${DAEMON}
    if [ $? -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi;
    echo ""
}

status(){
    # TODO: Query chef-client node state against server?
    #pgrep -f ${DAEMON}
    if [ $? -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi;
    echo ""
}

case "$1" in
  start)
    start 
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

