#!/bin/bash
# chkconfig:   - 25 75
# description: chef-deregistration-manager
# processname: chef-deregistration-manager

# Source function library.
if [ -e /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions;
fi;

DAEMON_DIR="/usr/bin"
DAEMON=""

start(){
    echo "Starting $DAEMON..."
    /bin/true
    if [ $? -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi;
    echo ""
}

stop(){
    if [ "`runlevel | cut -d " " -f 2`" == 0 ]; then
        echo "Stopping $DAEMON..."
        ${DAEMON_DIR}/${DAEMON} --chef-node `hostname -f`
    else
        echo "Skipping execution"
    fi;
    
    if [ $? -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi;
    echo ""
}

status(){
    /bin/true
    if [ $? -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi;
    echo ""
}

case "$1" in
  start)
    start 
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

