#!/bin/bash
### BEGIN INIT INFO
# Provides:          chef-deregistration-manager
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control chef-deregistraion-manager
# Description:       
### END INIT INFO

# Source function library.
if [ -e /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions;
fi;

DAEMON_DIR="/usr/bin"
DAEMON="chef-deregistration-manager"
CONFIG=/etc/chef-deregistration/manager.cfg

start(){
    echo "Starting $DAEMON..."
    /usr/bin/env python ${DAEMON_DIR}/${DAEMON} ${CONFIG}
    log_end_msg $?
}

stop(){
    echo "Stopping $DAEMON..."
    pkill -f ${DAEMON}
    log_end_msg $?
}

status(){
    pgrep -f ${DAEMON}
    log_end_msg $?
}

case "$1" in
  start)
    start 
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

