#!/bin/bash
### BEGIN INIT INFO
# Provides:          chef-deregistration-manager
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0
# Short-Description: Issue chef registration commands
# Description:       
### END INIT INFO

# Source function library.
if [ -e /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions;
fi;

DAEMON_DIR="/opt/chef-registration/bin"
DAEMON="registration-client"

start(){
    echo "Starting $DAEMON..."
    /bin/true
    log_end_msg $?
}

stop(){
    if [ "`runlevel | cut -d " " -f 2`" == 0 ]; then
        echo "Stopping $DAEMON..."
        ${DAEMON_DIR}/${DAEMON} --chef-node `hostname -f` --instance-id `curl "http://169.254.169.254/1.0/meta-data/instance-id"`
        log_end_msg $?
    else
        echo "Incorrect runlevel, No-op";
        /bin/true
        log_end_msg $?
    fi;
}

status(){
    /bin/true
    log_end_msg $?
}

case "$1" in
  start)
    start 
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

